# Automatically generated by Pynguin.
import file1 as module0


def test_case_0():
    var0 = module0.foo()
    assert var0 == 1
    var1 = module0.foo()
    assert var1 == 1
    var2 = module0.foo()
    assert var2 == 1
    var3 = module0.foo()
    assert var3 == 1
    var4 = module0.foo()
    assert var4 == 1
    var5 = module0.foo()
    assert var5 == 1
    var6 = module0.foo()
    assert var6 == 1
    var7 = module0.foo()
    assert var7 == 1
    var8 = module0.foo()
    assert var8 == 1
    var9 = module0.foo()
    assert var9 == 1
    var10 = module0.foo()
    assert var10 == 1
    var11 = module0.foo()
    assert var11 == 1
    var12 = module0.foo()
    assert var12 == 1
    var13 = module0.foo()
    assert var13 == 1
    var14 = module0.foo()
    assert var14 == 1


def test_case_1():
    var0 = module0.foo()
    assert var0 == 1
    var1 = module0.foo()
    assert var1 == 1
    var2 = module0.foo()
    assert var2 == 1
    var3 = module0.foo()
    assert var3 == 1
    var4 = module0.foo()
    assert var4 == 1
    var5 = module0.foo()
    assert var5 == 1
    var6 = module0.foo()
    assert var6 == 1
    var7 = module0.foo()
    assert var7 == 1
    var8 = module0.foo()
    assert var8 == 1
    var9 = module0.foo()
    assert var9 == 1
    var10 = module0.foo()
    assert var10 == 1
    var11 = module0.foo()
    assert var11 == 1
    var12 = module0.foo()
    assert var12 == 1
    var13 = module0.foo()
    assert var13 == 1
    var14 = module0.foo()
    assert var14 == 1
    var15 = module0.foo()
    assert var15 == 1
    var16 = module0.foo()
    assert var16 == 1
    var17 = module0.foo()
    assert var17 == 1
    var18 = module0.foo()
    assert var18 == 1
    var19 = module0.foo()
    assert var19 == 1
    var20 = module0.foo()
    assert var20 == 1
    var21 = module0.foo()
    assert var21 == 1
    var22 = module0.foo()
    assert var22 == 1
    var23 = module0.foo()
    assert var23 == 1
    var24 = module0.foo()
    assert var24 == 1
    var25 = module0.foo()
    assert var25 == 1
    var26 = module0.foo()
    assert var26 == 1
    var27 = module0.foo()
    assert var27 == 1
    var28 = module0.foo()
    assert var28 == 1
    var29 = module0.foo()
    assert var29 == 1
    var30 = module0.foo()
    assert var30 == 1
    var31 = module0.foo()
    assert var31 == 1
    var32 = module0.foo()
    assert var32 == 1
    var33 = module0.foo()
    assert var33 == 1


def test_case_2():
    var0 = module0.foo()
    assert var0 == 1
    var1 = module0.foo()
    assert var1 == 1
    var2 = module0.foo()
    assert var2 == 1
    var3 = module0.foo()
    assert var3 == 1
    var4 = module0.foo()
    assert var4 == 1
    var5 = module0.foo()
    assert var5 == 1
    var6 = module0.foo()
    assert var6 == 1
    var7 = module0.foo()
    assert var7 == 1
    var8 = module0.foo()
    assert var8 == 1
    var9 = module0.foo()
    assert var9 == 1
    var10 = module0.foo()
    assert var10 == 1
    var11 = module0.foo()
    assert var11 == 1
    var12 = module0.foo()
    assert var12 == 1
    var13 = module0.foo()
    assert var13 == 1
    var14 = module0.foo()
    assert var14 == 1
    var15 = module0.foo()
    assert var15 == 1
    var16 = module0.foo()
    assert var16 == 1
    var17 = module0.foo()
    assert var17 == 1
    var18 = module0.foo()
    assert var18 == 1
    var19 = module0.foo()
    assert var19 == 1
    var20 = module0.foo()
    assert var20 == 1
    var21 = module0.foo()
    assert var21 == 1
    var22 = module0.foo()
    assert var22 == 1
    var23 = module0.foo()
    assert var23 == 1
    var24 = module0.foo()
    assert var24 == 1
    var25 = module0.foo()
    assert var25 == 1
    var26 = module0.foo()
    assert var26 == 1
    var27 = module0.foo()
    assert var27 == 1
    var28 = module0.foo()
    assert var28 == 1
    var29 = module0.foo()
    assert var29 == 1
    var30 = module0.foo()
    assert var30 == 1
    var31 = module0.foo()
    assert var31 == 1
    var32 = module0.foo()
    assert var32 == 1
    var33 = module0.foo()
    assert var33 == 1
    var34 = module0.foo()
    assert var34 == 1
    var35 = module0.foo()
    assert var35 == 1
    var36 = module0.foo()
    assert var36 == 1
    var37 = module0.foo()
    assert var37 == 1
    var38 = module0.foo()
    assert var38 == 1


def test_case_3():
    var0 = module0.foo()
    assert var0 == 1
    var1 = module0.foo()
    assert var1 == 1
    var2 = module0.foo()
    assert var2 == 1
    var3 = module0.foo()
    assert var3 == 1
    var4 = module0.foo()
    assert var4 == 1
    var5 = module0.foo()
    assert var5 == 1
    var6 = module0.foo()
    assert var6 == 1
    var7 = module0.foo()
    assert var7 == 1
    var8 = module0.foo()
    assert var8 == 1
    var9 = module0.foo()
    assert var9 == 1
    var10 = module0.foo()
    assert var10 == 1
    var11 = module0.foo()
    assert var11 == 1
    var12 = module0.foo()
    assert var12 == 1
    var13 = module0.foo()
    assert var13 == 1
    var14 = module0.foo()
    assert var14 == 1
    var15 = module0.foo()
    assert var15 == 1
    var16 = module0.foo()
    assert var16 == 1
    var17 = module0.foo()
    assert var17 == 1
    var18 = module0.foo()
    assert var18 == 1
    var19 = module0.foo()
    assert var19 == 1
    var20 = module0.foo()
    assert var20 == 1
    var21 = module0.foo()
    assert var21 == 1
    var22 = module0.foo()
    assert var22 == 1
    var23 = module0.foo()
    assert var23 == 1
    var24 = module0.foo()
    assert var24 == 1
    var25 = module0.foo()
    assert var25 == 1
    var26 = module0.foo()
    assert var26 == 1
    var27 = module0.foo()
    assert var27 == 1
    var28 = module0.foo()
    assert var28 == 1


def test_case_4():
    var0 = module0.foo()
    assert var0 == 1
    var1 = module0.foo()
    assert var1 == 1
    var2 = module0.foo()
    assert var2 == 1
    var3 = module0.foo()
    assert var3 == 1
    var4 = module0.foo()
    assert var4 == 1
    var5 = module0.foo()
    assert var5 == 1
    var6 = module0.foo()
    assert var6 == 1
    var7 = module0.foo()
    assert var7 == 1
    var8 = module0.foo()
    assert var8 == 1
    var9 = module0.foo()
    assert var9 == 1
    var10 = module0.foo()
    assert var10 == 1
    var11 = module0.foo()
    assert var11 == 1
    var12 = module0.foo()
    assert var12 == 1
    var13 = module0.foo()
    assert var13 == 1
    var14 = module0.foo()
    assert var14 == 1
    var15 = module0.foo()
    assert var15 == 1
    var16 = module0.foo()
    assert var16 == 1
    var17 = module0.foo()
    assert var17 == 1
    var18 = module0.foo()
    assert var18 == 1
    var19 = module0.foo()
    assert var19 == 1
    var20 = module0.foo()
    assert var20 == 1


def test_case_5():
    var0 = module0.foo()
    assert var0 == 1
    var1 = module0.foo()
    assert var1 == 1


def test_case_6():
    var0 = module0.foo()
    assert var0 == 1
    var1 = module0.foo()
    assert var1 == 1
    var2 = module0.foo()
    assert var2 == 1
    var3 = module0.foo()
    assert var3 == 1
    var4 = module0.foo()
    assert var4 == 1
    var5 = module0.foo()
    assert var5 == 1
    var6 = module0.foo()
    assert var6 == 1
    var7 = module0.foo()
    assert var7 == 1
    var8 = module0.foo()
    assert var8 == 1
    var9 = module0.foo()
    assert var9 == 1
    var10 = module0.foo()
    assert var10 == 1
    var11 = module0.foo()
    assert var11 == 1
    var12 = module0.foo()
    assert var12 == 1
    var13 = module0.foo()
    assert var13 == 1
    var14 = module0.foo()
    assert var14 == 1
    var15 = module0.foo()
    assert var15 == 1
    var16 = module0.foo()
    assert var16 == 1
    var17 = module0.foo()
    assert var17 == 1
    var18 = module0.foo()
    assert var18 == 1
    var19 = module0.foo()
    assert var19 == 1
    var20 = module0.foo()
    assert var20 == 1
    var21 = module0.foo()
    assert var21 == 1
    var22 = module0.foo()
    assert var22 == 1
    var23 = module0.foo()
    assert var23 == 1
    var24 = module0.foo()
    assert var24 == 1
    var25 = module0.foo()
    assert var25 == 1
    var26 = module0.foo()
    assert var26 == 1
    var27 = module0.foo()
    assert var27 == 1
    var28 = module0.foo()
    assert var28 == 1
    var29 = module0.foo()
    assert var29 == 1
    var30 = module0.foo()
    assert var30 == 1
    var31 = module0.foo()
    assert var31 == 1
    var32 = module0.foo()
    assert var32 == 1
    var33 = module0.foo()
    assert var33 == 1
    var34 = module0.foo()
    assert var34 == 1


def test_case_7():
    var0 = module0.foo()
    assert var0 == 1
    var1 = module0.foo()
    assert var1 == 1
    var2 = module0.foo()
    assert var2 == 1
    var3 = module0.foo()
    assert var3 == 1
    var4 = module0.foo()
    assert var4 == 1
    var5 = module0.foo()
    assert var5 == 1
    var6 = module0.foo()
    assert var6 == 1
    var7 = module0.foo()
    assert var7 == 1
    var8 = module0.foo()
    assert var8 == 1
    var9 = module0.foo()
    assert var9 == 1
    var10 = module0.foo()
    assert var10 == 1
    var11 = module0.foo()
    assert var11 == 1
    var12 = module0.foo()
    assert var12 == 1
    var13 = module0.foo()
    assert var13 == 1
    var14 = module0.foo()
    assert var14 == 1
    var15 = module0.foo()
    assert var15 == 1
    var16 = module0.foo()
    assert var16 == 1
    var17 = module0.foo()
    assert var17 == 1
    var18 = module0.foo()
    assert var18 == 1
    var19 = module0.foo()
    assert var19 == 1
    var20 = module0.foo()
    assert var20 == 1
    var21 = module0.foo()
    assert var21 == 1
    var22 = module0.foo()
    assert var22 == 1
    var23 = module0.foo()
    assert var23 == 1
    var24 = module0.foo()
    assert var24 == 1
    var25 = module0.foo()
    assert var25 == 1
    var26 = module0.foo()
    assert var26 == 1
    var27 = module0.foo()
    assert var27 == 1
    var28 = module0.foo()
    assert var28 == 1
    var29 = module0.foo()
    assert var29 == 1
    var30 = module0.foo()
    assert var30 == 1
    var31 = module0.foo()
    assert var31 == 1
    var32 = module0.foo()
    assert var32 == 1
    var33 = module0.foo()
    assert var33 == 1
    var34 = module0.foo()
    assert var34 == 1
    var35 = module0.foo()
    assert var35 == 1
    var36 = module0.foo()
    assert var36 == 1
    var37 = module0.foo()
    assert var37 == 1
    var38 = module0.foo()
    assert var38 == 1
    var39 = module0.foo()
    assert var39 == 1


def test_case_8():
    var0 = module0.foo()
    assert var0 == 1
    var1 = module0.foo()
    assert var1 == 1
    var2 = module0.foo()
    assert var2 == 1
    var3 = module0.foo()
    assert var3 == 1
    var4 = module0.foo()
    assert var4 == 1
    var5 = module0.foo()
    assert var5 == 1
    var6 = module0.foo()
    assert var6 == 1
    var7 = module0.foo()
    assert var7 == 1
    var8 = module0.foo()
    assert var8 == 1
    var9 = module0.foo()
    assert var9 == 1
    var10 = module0.foo()
    assert var10 == 1
    var11 = module0.foo()
    assert var11 == 1
    var12 = module0.foo()
    assert var12 == 1
    var13 = module0.foo()
    assert var13 == 1
    var14 = module0.foo()
    assert var14 == 1
    var15 = module0.foo()
    assert var15 == 1
    var16 = module0.foo()
    assert var16 == 1
    var17 = module0.foo()
    assert var17 == 1
    var18 = module0.foo()
    assert var18 == 1
    var19 = module0.foo()
    assert var19 == 1
    var20 = module0.foo()
    assert var20 == 1
    var21 = module0.foo()
    assert var21 == 1
    var22 = module0.foo()
    assert var22 == 1
    var23 = module0.foo()
    assert var23 == 1
    var24 = module0.foo()
    assert var24 == 1
    var25 = module0.foo()
    assert var25 == 1
    var26 = module0.foo()
    assert var26 == 1
    var27 = module0.foo()
    assert var27 == 1
    var28 = module0.foo()
    assert var28 == 1
    var29 = module0.foo()
    assert var29 == 1
    var30 = module0.foo()
    assert var30 == 1
    var31 = module0.foo()
    assert var31 == 1
    var32 = module0.foo()
    assert var32 == 1
    var33 = module0.foo()
    assert var33 == 1
    var34 = module0.foo()
    assert var34 == 1
    var35 = module0.foo()
    assert var35 == 1
    var36 = module0.foo()
    assert var36 == 1
    var37 = module0.foo()
    assert var37 == 1


def test_case_9():
    var0 = module0.foo()
    assert var0 == 1
    var1 = module0.foo()
    assert var1 == 1
    var2 = module0.foo()
    assert var2 == 1
