# Automatically generated by Pynguin.
import file1 as module0


def test_case_0():
    var0 = module0.foo()
    assert var0 == 9
    var1 = module0.foo()
    assert var1 == 9
    var2 = module0.foo()
    assert var2 == 9
    var3 = module0.foo()
    assert var3 == 9
    var4 = module0.foo()
    assert var4 == 9
    var5 = module0.foo()
    assert var5 == 9
    var6 = module0.foo()
    assert var6 == 9
    var7 = module0.foo()
    assert var7 == 9
    var8 = module0.foo()
    assert var8 == 9
    var9 = module0.foo()
    assert var9 == 9
    var10 = module0.foo()
    assert var10 == 9
    var11 = module0.foo()
    assert var11 == 9
    var12 = module0.foo()
    assert var12 == 9
    var13 = module0.foo()
    assert var13 == 9
    var14 = module0.foo()
    assert var14 == 9
    var15 = module0.foo()
    assert var15 == 9
    var16 = module0.foo()
    assert var16 == 9
    var17 = module0.foo()
    assert var17 == 9
    var18 = module0.foo()
    assert var18 == 9
    var19 = module0.foo()
    assert var19 == 9
    var20 = module0.foo()
    assert var20 == 9
    var21 = module0.foo()
    assert var21 == 9
    var22 = module0.foo()
    assert var22 == 9
    var23 = module0.foo()
    assert var23 == 9
    var24 = module0.foo()
    assert var24 == 9
    var25 = module0.foo()
    assert var25 == 9
    var26 = module0.foo()
    assert var26 == 9


def test_case_1():
    var0 = module0.foo()
    assert var0 == 9
    var1 = module0.foo()
    assert var1 == 9
    var2 = module0.foo()
    assert var2 == 9
    var3 = module0.foo()
    assert var3 == 9
    var4 = module0.foo()
    assert var4 == 9
    var5 = module0.foo()
    assert var5 == 9
    var6 = module0.foo()
    assert var6 == 9
    var7 = module0.foo()
    assert var7 == 9
    var8 = module0.foo()
    assert var8 == 9
    var9 = module0.foo()
    assert var9 == 9
    var10 = module0.foo()
    assert var10 == 9
    var11 = module0.foo()
    assert var11 == 9
    var12 = module0.foo()
    assert var12 == 9
    var13 = module0.foo()
    assert var13 == 9
    var14 = module0.foo()
    assert var14 == 9
    var15 = module0.foo()
    assert var15 == 9
    var16 = module0.foo()
    assert var16 == 9
    var17 = module0.foo()
    assert var17 == 9
    var18 = module0.foo()
    assert var18 == 9
    var19 = module0.foo()
    assert var19 == 9
    var20 = module0.foo()
    assert var20 == 9
    var21 = module0.foo()
    assert var21 == 9
    var22 = module0.foo()
    assert var22 == 9
    var23 = module0.foo()
    assert var23 == 9
    var24 = module0.foo()
    assert var24 == 9
    var25 = module0.foo()
    assert var25 == 9
    var26 = module0.foo()
    assert var26 == 9
    var27 = module0.foo()
    assert var27 == 9
    var28 = module0.foo()
    assert var28 == 9
    var29 = module0.foo()
    assert var29 == 9
    var30 = module0.foo()
    assert var30 == 9
    var31 = module0.foo()
    assert var31 == 9
    var32 = module0.foo()
    assert var32 == 9
    var33 = module0.foo()
    assert var33 == 9


def test_case_2():
    var0 = module0.foo()
    assert var0 == 9
    var1 = module0.foo()
    assert var1 == 9
    var2 = module0.foo()
    assert var2 == 9
    var3 = module0.foo()
    assert var3 == 9


def test_case_3():
    var0 = module0.foo()
    assert var0 == 9
    var1 = module0.foo()
    assert var1 == 9
    var2 = module0.foo()
    assert var2 == 9
    var3 = module0.foo()
    assert var3 == 9
    var4 = module0.foo()
    assert var4 == 9
    var5 = module0.foo()
    assert var5 == 9
    var6 = module0.foo()
    assert var6 == 9
    var7 = module0.foo()
    assert var7 == 9
    var8 = module0.foo()
    assert var8 == 9
